# Generated by Django 4.0.3 on 2022-04-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.profile')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user.profile')),
            ],
        ),
    ]
