# Generated by Django 4.0.3 on 2022-04-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='user',
        ),
    ]
