# Generated by Django 4.0.3 on 2022-04-04 10:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_profile_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=tinymce.models.HTMLField(),
        ),
    ]
